project_id = "oyoifasethtkfkocppzs"

[functions.get-affiliate]
verify_jwt = false

[functions.get-affiliate-by-discord-id]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.confirm-sale]
verify_jwt = false
