project_id = "oyoifasethtkfkocppzs"

[functions.check-admin]
verify_jwt = false

[functions.confirm-sale]
verify_jwt = false

[functions.create-lead]
verify_jwt = false

[functions.get-affiliate]
verify_jwt = false

[functions.get-affiliate-by-discord-id]
verify_jwt = false

[functions.get-system-config]
verify_jwt = false

[functions.request-withdrawal]
verify_jwt = false
